/*
 * This program source code file is part of KiChad, a Codex-integrated downstream of KiCad.
 *
 * Copyright (C) 2026 KiChad Developers
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 */

#include <boost/test/unit_test.hpp>

#include <kicad/codex/schematic_svg_artifact_validator.h>

#include <filesystem>
#include <fstream>
#include <string_view>

#include <kiid.h>
#include <wx/filename.h>


namespace
{

class SVG_FIXTURE
{
public:
    SVG_FIXTURE()
    {
        m_root = std::filesystem::path( wxFileName::GetTempDir().ToStdString() )
                 / ( "kichad-schematic-svg-validator-"
                     + KIID().AsString().ToStdString() );
        std::filesystem::create_directories( m_root );
    }

    ~SVG_FIXTURE()
    {
        std::error_code ignored;
        std::filesystem::remove_all( m_root, ignored );
    }

    std::filesystem::path Write( const std::string& aName,
                                 const std::string& aSource )
    {
        const std::filesystem::path path = m_root / aName;
        std::ofstream output( path, std::ios::binary | std::ios::trunc );
        output << aSource;
        output.close();
        BOOST_REQUIRE( output.good() );
        return path;
    }

private:
    std::filesystem::path m_root;
};

} // namespace


BOOST_AUTO_TEST_SUITE( SchematicSvgArtifactValidator )


BOOST_AUTO_TEST_CASE( AcceptsNativeDrawingAndRejectsEventHandlers )
{
    SVG_FIXTURE fixture;
    const std::string valid =
            "<?xml version=\"1.0\"?>\n"
            "<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" "
            "width=\"100mm\" height=\"80mm\" viewBox=\"0 0 100 80\">"
            "<title>SVG Image created as controller.svg date 2026-07-19</title>"
            "<desc>Image generated by Eeschema-SVG</desc>"
            "<path d=\"M 0 0 L 10 10\"/></svg>\n";
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::SCHEMATIC_SVG_ARTIFACT_VALIDATOR::ValidateFile(
                    fixture.Write( "controller.svg", valid ), "controller", error ), error );

    error.clear();
    std::string child = valid;
    child.replace( child.find( "controller.svg" ),
                   std::string_view( "controller.svg" ).size(),
                   "controller-power.svg" );
    BOOST_CHECK_MESSAGE(
            KICHAD::SCHEMATIC_SVG_ARTIFACT_VALIDATOR::ValidateFile(
                    fixture.Write( "controller-power.svg", child ), "controller", error ),
            error );

    error.clear();
    std::string active = valid;
    active.replace( active.find( "<path " ), 6, "<path onclick=\"run()\" " );
    BOOST_CHECK( !KICHAD::SCHEMATIC_SVG_ARTIFACT_VALIDATOR::ValidateFile(
            fixture.Write( "controller.svg", active ), "controller", error ) );
    BOOST_CHECK( !error.empty() );
}


BOOST_AUTO_TEST_SUITE_END()
